<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
	<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<!-- Exibindo o nome -->
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<!-- Exibindo o total de tweets -->
								<?= $this->view->total_tweets['total_tweet'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<!-- Exibindo o total de pessoas que está seguindo -->
								<?= $this->view->total_seguindo['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<!-- Exibindo o total de seguidores -->
								<?= $this->view->total_seguidores['total_seguidores'] ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- Listando tweets -->

			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<!-- Nome do usuário que publicou e data/hora da publicação -->
						<p><strong><?=$tweet['nome']?></strong> <small><span class="text text-muted">- <?=$tweet['data']?></span></small></p>
						<!-- Conteúdo da publicação -->
						<p><?=$tweet['tweet']?></p>
						<br />

						<!-- Comparando se o id do usuário responsável pela publicação é o mesmo id do usuário da sessão. Caso for igual, ele pode apagar a publicação -->
						<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>

							<!-- Deletando o tweet que o usuário publicou -->
							<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>
								
								<form method="post" action="/remover_tweet?id=<?= $tweet['id']?>">
									<div class="col d-flex justify-content-end">
										<button type="submit" class="btn btn-danger"><small>Remover</small></button>
									</div>
								</form>

							<?php } ?>

						<?php } ?>	

					</div>
				</div>

			<?php } ?>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>